### ISSUE TITLE
exported WC TreeGrid sample uses EventTemplate with Grid instead of TreeGrid

### ISSUE THREAD

**Issue by HUSSAR-mtrela** [IgniteUI/igniteui-xplat-examples#399]
TreeGrid [xplat sample](https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/samples/grids/tree-grid/multi-column-headers-overview.json#L17) sample uses Grid Event Template instead of TreeGrid Event Template which is causing this build error:
![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/11665978/72e3a327-9da6-4b9f-8bbe-2b168a01a904)

Solution:
- copy this [event template](https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/code-gen-library/WebGridPinFirstGroupToggle/Web.ts) and save it with TreeGrid prefix
- use TreeGrid in the copied template instead of Grid
- update the TreeGrid [xplat sample](https://github.com/IgniteUI/igniteui-xplat-examples/blob/23.2.x/samples/grids/tree-grid/multi-column-headers-overview.json#L17) sample

**Comment by gmurray81** [comment]
Hmmm.... now that I'm thinking about this though.... maybe we should have some special dispensation for the grids where it will try to automagically adapt the type when you use that helper to match the main type, if possible. Since a lot of handlers may have been authored to point at one grid, but may work for all of them....

maybe we could have a special "type" you can use which will get replaced with the type of the target?

Do we think we have enough of these handlers @HUSSAR-mtrela @MayaKirova  that this would make sense?

Actually since we retain the base grid type, you may just be able to use the GridBaseDirective here instead of Grid or TreeGrid without any changes?

**Comment by skrustev** [comment]
@gmurray81 In this case the columns for the Tree Grid are also different, so another tree grid specific handlers are needed.
It doesn't seem like super critical for now to be able to replace type with the target type, there are a few templates that could be reused for Tree Grid as well, but I think we have yet to go through all of them for the Tree Grid.

It does seem to not apply variable type when specified like this and it works though, only negative is that an unused import is added as expected:
![image](https://github.com/IgniteUI/igniteui-xplat-examples/assets/3768136/3343f87a-82a6-4c4f-becd-06720dab95ad)
